### ISSUE TITLE
DevTernity is coming. Are you in?

### ISSUE THREAD

**Issue by devternity-conference** [athaun/athaun#1]
Hey @athaun 👋

**[DevTernity](https://devternity.com)** — the main developer conference of the year is finally here:

[![Conference program](https://devternity.com/images/speakers.png)](https://devternity.com)

➡️  Get your ticket now and save 200€: **https://devternity.com**

[![DevTernity call for action – are you in?](https://devternity.com/images/areyouin.gif)](https://devternity.com)

**Comment by athaun** [comment]
![image](https://user-images.githubusercontent.com/32278830/131918561-589b158a-c65f-4db2-a086-22195a07fa31.png)
